{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9ed3b96f-acaf-4ac6-a483-cdbb027c067d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "AUCA Big Data Analytics Final Project\n",
    "Part 1 — MongoDB Data Loading Script\n",
    "Loads: users, categories, products, transactions into MongoDB\n",
    "\"\"\"\n",
    "\n",
    "import json\n",
    "from pymongo import MongoClient, ASCENDING\n",
    "\n",
    "# Connect to MongoDB\n",
    "client = MongoClient(\"mongodb://localhost:27017/\")\n",
    "db = client[\"ecommerce_db\"]\n",
    "\n",
    "# ─────────────────────────────────────────\n",
    "# LOAD USERS\n",
    "# ─────────────────────────────────────────\n",
    "print(\"Loading users...\")\n",
    "with open(\"users.json\") as f:\n",
    "    users = json.load(f)\n",
    "db.users.drop()\n",
    "db.users.insert_many(users)\n",
    "db.users.create_index([(\"user_id\", ASCENDING)], unique=True)\n",
    "print(f\"  ✓ {db.users.count_documents({})} users loaded\")\n",
    "\n",
    "# ─────────────────────────────────────────\n",
    "# LOAD CATEGORIES\n",
    "# ─────────────────────────────────────────\n",
    "print(\"Loading categories...\")\n",
    "with open(\"categories.json\") as f:\n",
    "    categories = json.load(f)\n",
    "db.categories.drop()\n",
    "db.categories.insert_many(categories)\n",
    "db.categories.create_index([(\"category_id\", ASCENDING)], unique=True)\n",
    "print(f\"  ✓ {db.categories.count_documents({})} categories loaded\")\n",
    "\n",
    "# ─────────────────────────────────────────\n",
    "# LOAD PRODUCTS\n",
    "# ─────────────────────────────────────────\n",
    "print(\"Loading products...\")\n",
    "with open(\"products.json\") as f:\n",
    "    products = json.load(f)\n",
    "db.products.drop()\n",
    "db.products.insert_many(products)\n",
    "db.products.create_index([(\"product_id\", ASCENDING)], unique=True)\n",
    "db.products.create_index([(\"category_id\", ASCENDING)])\n",
    "print(f\"  ✓ {db.products.count_documents({})} products loaded\")\n",
    "\n",
    "# ─────────────────────────────────────────\n",
    "# LOAD TRANSACTIONS\n",
    "# ─────────────────────────────────────────\n",
    "print(\"Loading transactions...\")\n",
    "with open(\"transactions.json\") as f:\n",
    "    transactions = json.load(f)\n",
    "db.transactions.drop()\n",
    "db.transactions.insert_many(transactions)\n",
    "db.transactions.create_index([(\"transaction_id\", ASCENDING)], unique=True)\n",
    "db.transactions.create_index([(\"user_id\", ASCENDING)])\n",
    "db.transactions.create_index([(\"timestamp\", ASCENDING)])\n",
    "print(f\"  ✓ {db.transactions.count_documents({})} transactions loaded\")\n",
    "\n",
    "print(\"\\nAll collections loaded into 'ecommerce_db'\")\n",
    "client.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
